// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc_m2oBRXRBzK8xT5FSMwHtVOslVaLGvg',
    appId: '1:654615274079:web:9e96cadc0412f290f1b1ea',
    messagingSenderId: '654615274079',
    projectId: 'qiuqiao-abacf',
    authDomain: 'qiuqiao-abacf.firebaseapp.com',
    storageBucket: 'qiuqiao-abacf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0bN1YV74t2oiq8abE6EXlnguXcszpLU',
    appId: '1:654615274079:android:9463e74f923419acf1b1ea',
    messagingSenderId: '654615274079',
    projectId: 'qiuqiao-abacf',
    storageBucket: 'qiuqiao-abacf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc_m2oBRXRBzK8xT5FSMwHtVOslVaLGvg',
    appId: '1:654615274079:web:0ad9095dfa65823df1b1ea',
    messagingSenderId: '654615274079',
    projectId: 'qiuqiao-abacf',
    authDomain: 'qiuqiao-abacf.firebaseapp.com',
    storageBucket: 'qiuqiao-abacf.firebasestorage.app',
  );
}
